---
- name: Create systemd service file
  template:
    src: node.service.j2
    dest: "/etc/systemd/system/{{ node_service_name }}.service"
    mode: '0644'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable service
  systemd:
    name: "{{ node_service_name }}"
    enabled: yes 